function s = func_decode_row_col(filename,tail_info)
    fid = fopen(filename);
    sop = fscanf(fid,'%d',4);
    parameter = fscanf(fid,'%g',2);
    dat = fscanf(fid,'%d%d%g',inf);
    dat = transpose(reshape(dat,3,[]));
    ROW = dat(end-tail_info,1);
    COL = dat(end-tail_info:2); 
    s = struct(...
        'frame_id' , sop(1) ...
        ,'len' , sop(2) ...
        ,'cnt' , sop(3) ...
        ,'iter_cnt' , sop(4) ...
        ,'parameter',parameter ...
        ,'vector', [ROW,COL] ...
    );
    fclose all;
end