function s = func_decode_vector_1(filename,format1,format2)
    fid = fopen(filename);
    tmp = fscanf(fid,format1,4);
    frame_id = tmp(1);
    len      = tmp(2);
    cnt      = tmp(3);
    iter_cnt = tmp(4);
    tmp = fscanf(fid,format2,Inf);
    vector   = tmp(1:end-3);
    s = struct( ...
    'frame_id' , frame_id ...
    ,'len' , len ...
    ,'cnt' , cnt ...
    ,'iter_cnt' , iter_cnt ...
    ,'vector', vector ...
    );
    fclose all;
end